@startchen ER-diagram

entity Event {
    Name
    Description
    Location
    Time {
        StartDateTime
        EndDateTime
    }
    GoingEmoji
    NotGoingEmoji
}

relationship Answer {
    IsGoing
}

relationship Created {
}

entity Person {
    Discord_id <<key>>
    Name
}

Event -N- Answer
Answer -M- Person

Event -N- Created
Created -1- Person

entity BeerCase {
    Time
    Amount
}

relationship Owes {
}

BeerCase -1- Owes
Owes -N- Person

entity Channel {
    Discord_id <<key>>
    Name
}

entity Message {
    Discord_id <<key>>
    Time
    Text
}

relationship Has {
}

Channel -1- Has
Has -1- Event

relationship Sent {
}

Person -1- Sent
Sent -N- Message

relationship In {
}

Message -N- In
In -1- Channel


@endchen